name: MAIN

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Icarus Verilog
      run: |
        sudo apt-get update
        sudo apt-get install -y iverilog


    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      run: pip install cocotb

    - name: Add cocotbext to PYTHONPATH and run tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: make -C tests
